# Generated by Django 6.0.1 on 2026-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
